name: mac

on: 
  push:

jobs:

  build-mac:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        cd ../..
        git clone https://github.com/open-ephys/plugin-GUI.git --branch development-juce6
        cd plugin-GUI/Build && cmake -G "Xcode" ..
    - name: build
      run: |
        cd Build
        cmake -G "Xcode" ..
        xcodebuild -configuration Release
        install_name_tool -change /usr/local/lib/libzmq.5.dylib @rpath/libzmq.5.dylib Release/NetworkEvents.bundle/Contents/MacOS/NetworkEvents
#    - name: test
#      run: cd build && ctest
    - name: deploy
      if: github.ref == 'refs/heads/master'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
        build_dir: "Build/Release"
        repo: ${{ github.event.repository.name }}
        package: ${{ github.event.repository.name }}-mac
      run: |
        plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]" | tail -1)
        tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        new_plugin_ver=$tag-API$plugin_api
        mkdir plugins 
        cp -r $build_dir/*.bundle plugins
        mkdir shared	
        cp -r libs/macos/bin/* shared
        zipfile=${package}_${new_plugin_ver}.zip
        zip -r -X $zipfile plugins shared
        curl -H "X-JFrog-Art-Api:$artifactoryApiKey" -T $zipfile "https://openephys.jfrog.io/artifactory/NetworkEvents-plugin/mac/$zipfile"